Incoming
investr777/RabbitMQ pull request #5
Opened 2022-03-12 09:01 UTC by AliJester

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/build.gradle
> +    implementation(Spring.Bom.starter)
remove it

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/build.gradle
> +    implementation(project(ProjectDeps.cmnRabbitmq))
static import

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/config/MainConfig.java
> +
needless blank line

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/config/MainConfig.java
> +    IncomingService defaultIncomingServiceService(
incomingService

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/service/DefaultIncomingService.java
> +    private final String routingKey;
it's necessary, because we have fonaut binding

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/service/DefaultIncomingService.java
> +    private final String routingKey;
routingKey should be null

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +    @GetMapping("/incoming/{text}")
Post

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +        val message = objectMapper.writeValueAsBytes(text);
wrap try-catch

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +    public String getIncoming(@PathVariable("text") String text) throws IOException {
void

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +    @GetMapping("/incoming/{text}")
@ResponseStatus

2022-03-12 09:21 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +    @GetMapping("/defaultExchange/{text}")
remove it

2022-03-12 13:36 UTC, investr777 requested changes

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/service/DefaultIncomingService.java
> +
remove blank line

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/build.gradle.kts
> +}
add blank line after

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/IncomingExceptionHandler.java
> +
remove blank lines

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +@RequestMapping("/api/incoming")
add /api via spring application config

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +
remove blank line

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +    public void getIncoming(@RequestBody String text) {
Do we need get controller?

2022-03-12 13:36 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/resources/banner.txt
> +,--.                                    ,--.                    ,--.  ,--.                      ,--. ,--.
use standart style)

2022-03-14 05:16 UTC, investr777 requested changes

2022-03-14 05:16 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/IncomingExceptionHandler.java
> +    ResponseEntity<ErrorResponse> handleIncomingMessageParseException(IncomingMessageParseException ex) {
What about other exceptions?

2022-03-14 05:16 UTC, investr777 commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/controller/IncomingController.java
> +            val message = objectMapper.writeValueAsBytes(text);
I think, it should be in service, not in controller

2022-03-14 05:16 UTC, investr777 commented on sources/rmq/app/src/main/java/rmq/app/App.java
> +package rmq.app;
Is it necessary?

2022-03-14 05:16 UTC, investr777 commented on sources/rmq/modules/cmn-rabbitmq/src/main/java/net/its/rmq/cmn/rabbitmq/publisher/DefaultMessagePublisher.java
> +    public void publish(String exchange, String routingKey, byte[] message) throws IOException {
It's bad. This publisher should throws custom Exception, but not IOException

2022-03-14 06:58 UTC, AliJester commented on sources/rmq/app-incoming-handler/src/main/java/net/its/rmq/incoming/web/IncomingExceptionHandler.java
> +    ResponseEntity<ErrorResponse> handleIncomingMessageParseException(IncomingMessageParseException ex) {
I added common exception just in case. In general there are only two exceptions to occur.

2022-03-14 08:44 UTC, investr777 approved these changes

2022-03-14 08:45 UTC, merged